#ifndef MATHENUMS_H
#define MATHENUMS_H

enum MathVariant {NORMAL, BOLD, ITALIC, BOLD_ITALIC, DOUBLE_STRUCK, 
	BOLD_FRAKTUR, SCRIPT, BOLD_SCRIPT, FRAKTUR, SANS_SERIF, BOLD_SANS_SERIF,
	SANS_SERIF_ITALIC, SANS_SERIF_BOLD_ITALIC, MONOSPACE};

extern const char *mathvariantnames[14];
 
#endif
